version: "3.8"

services:
  frontend:
    env_file: ".env"
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    networks:
      - buff163-scraper
    depends_on:
      - api

  api:
    env_file: ".env"
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${REACT_APP_API_PORT}:${REACT_APP_API_PORT}"
    networks:
      - buff163-scraper
    depends_on:
      - scraper-service

  scraper-service:
    env_file: ".env"
    container_name: scraper-service
    build:
      context: ./scraper-service
      dockerfile: Dockerfile
    ports:
      - "${SCRAPER_SERVICE_PORT}:${SCRAPER_SERVICE_PORT}"
    networks:
      - buff163-scraper
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.0.28-xenial
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    networks:
      - buff163-scraper
    volumes:
      - mongo-data:/data/db

networks:
  buff163-scraper:
    driver: bridge

volumes:
  mongo-data:
    driver: local