version: "3.8"

services:
  item-scraper:
    env_file: ".env"
    container_name: item-scraper
    build:
      context: ./item-scraper
      dockerfile: Dockerfile
    ports:
      - "${ITEM_SCRAPER_PORT}:${ITEM_SCRAPER_PORT}"
    networks:
      - buff163-scraper
    depends_on:
      - mongo

  sticker-scraper:
    env_file: ".env"
    container_name: sticker-scraper
    build:
      context: ./sticker-scraper
      dockerfile: Dockerfile
    ports:
      - "${STICKER_SCRAPER_PORT}:${STICKER_SCRAPER_PORT}"
    networks:
      - buff163-scraper
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.0.28-xenial
    ports:
      - "27017:27017"
    networks:
      - buff163-scraper
    volumes:
      - mongo-data:/data/db

networks:
  buff163-scraper:
    driver: bridge

volumes:
  mongo-data:
    driver: local